refactor: Changement sex à genre
CDPVD/cdpvd_dashboards_store pull request #5
Opened 2024-12-11 20:59 UTC by gelinassCSSRS

# Objectives of the Pull Request ? 
> Describe the high level purpose of your pull request. What are you trying to achieve ? How are you doing it ?

# What is left out of the Pull Request ? 
> Describe what is not included in the pull request. Why did you not include it in the PR. What are the next steps ?

# How to run the pull request ?
> Provide the code required to run the pull request. This is the code that will be used to review your pull request. **The provided code must work as-is. If a DBT error is raised while running the code, the PR will be rejected. The following code / placeholder is only provided as documentation / helper to get you started and you will need to adjust it.**

```bash
# Assuming you are in a folder containing both the core.data.store and the <cssXX>.data.store folder.
# Update the code
cd core.dashboards_store
git checkout feature/<feature_name>
git pull
# Might be required if you update either the poetry file or the lock file
# poetry shell && poetry lock && poetry install 
cd ../<cssXX>.dashboards_store
git checkout feature/<feature_name>
git pull  
# Might be required if you add a new DBT dependency
# dbt deps
# Run dbt 
dbt build --select +tag:<my resources tag>+
```

# Checklist
> Please, read carefully each item before checking it. Your PR's review might be delayed otherwise.

* **Code** :
  * [x] The code I'm asking a review for is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x] My code follows the conventions described in the `contribution guide`.
  * [x] My `models` / `seeds` / `adapters` are tested and documented in DBT 9through the `yaml` files.
  * I have a added a new **mandatory seed** / a new **mandatory adapter** : 
    * [x] I have you populated the `tooling/nightly` project with my new seed / adapter.
    * [x] An exemple of how to populate the adapter can be found in the `analysis` folder.
  * I have added a new **dashboard** : 
    * [x] I have updated the `core.dashboards_store/tooling/template/{{ cookiecutter.css_short_name + '.dashboards_store' }}/dbt_project.yml` file with my new dashboard. 
    * [ ] I have added a new `doc` page in the `core.dashboards_store/tooling/docs/content/` appropriate folder, describing what my dashboards does and how to configure it.
    * [x] The dashboard is saved with `.pbit` extension, **not** a `.pbix` extension, so it doesn't contains any data.
  * [x] I have called `sqfmt .` to format my code, and **made sure my code was still running as expected after having been reformated**.
* **Documentation** : 
  * [ ]  I have updated the documentation (README) accordingly to my changes.
  * [x]  The models I have added are documented in a `schema.yml` file.
* **Pull-request** : 
  * [x]  My merge message is prefixed with a `commitizen` key word so it looks something like `<feat|fix|chore|doc|refactor|perf|style>: foo bar`**
  * [x]  The code *provided to run the pull request* is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x]  My pull request is documented. I have explained the needs for the PR, what was left out of the it and why.
  * [x]  I have carefully reviewd each changes made to a file and made sure the files included on the PR were actually added on purpose.
  * [x]  I have assignee at least **1** people to review my PR.

2024-12-13 14:47 UTC, jalluard commented
Allo Sylvain,

Dans l'état actuel, c'est très compliqué de reviewer ta PR... Au vu du titre de ta PR et de l'objectif principal de ta PR, je m'attends a voir des changements de la variable `sex` à `genre` à différents endroits. 

Lorsque je vais voir tes commits je vois 6 fois le même commit... la comme ca, je m'imagine que tu as eu quelques oublis et que tu as modifié la variable `sex` à `genre` de façon séquentielle.

![image](https://github.com/user-attachments/assets/9f5664bb-2b62-40f0-b46d-442af4380971)

Déjà ici, il te faudrait réorganiser tes commits car ca fait pas de sens d'avoir 5 fois le même commit. Lorsque je regarde d'un peu plus près ce que fait chacun de tes commits, je vois : 

1. un commit ou tu fais un changement de licence (donc ton libellé de commit ne fait pas de sens)
2. un commit avec un saut de ligne...  (donc ton libellé de commit ne fait pas de sens)
3. un commit ou tu fais un changement de licence (donc ton libellé de commit ne fait pas de sens)
4. un commit ou tu ajoutes un pbit (donc ton libellé de commit ne fait pas de sens)
5. un commit initial ou il se passe pas mal de chose, trop de choses... (modification du dbt_project, ajout d'une table, actualisation d'un schema. donc la aussi le libellé de ton commit ne fait pas de sens

On ne peut pas intégrer cette PR tel quel. il faut reorganiser tes commits et preciser clairement ce que tu fais ds ta PR. il n'y a pas qu'un "Changement `sex` à `genre` "

2024-12-13 14:56 UTC, busquef commented
> Allo Sylvain,
> 
> Dans l'état actuel, c'est très compliqué de reviewer ta PR... Au vu du titre de ta PR et de l'objectif principal de ta PR, je m'attends a voir des changements de la variable `sex` à `genre` à différents endroits.
> 
> Lorsque je vais voir tes commits je vois 6 fois le même commit... la comme ca, je m'imagine que tu as eu quelques oublis et que tu as modifié la variable `sex` à `genre` de façon séquentielle.
> 
> ![image](https://private-user-images.githubusercontent.com/159054441/395595271-9f5664bb-2b62-40f0-b46d-442af4380971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMDE4NjgsIm5iZiI6MTczNDEwMTU2OCwicGF0aCI6Ii8xNTkwNTQ0NDEvMzk1NTk1MjcxLTlmNTY2NGJiLTJiNjItNDBmMC1iNDZkLTQ0MmFmNDM4MDk3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxM1QxNDUyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZWM2NDcyZjY5YjZmOGRlZDNjMzRhNzVkMjkxZWEzNjFjNzZlNGY0ZjMxMDdhNDdlYjM4ZDI1ZWNmMzNmMWVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._8nWulq8cgyTHptL5HxIG9IOpj8BJBS8oSzMAjehNqs)
> 
> Déjà ici, il te faudrait réorganiser tes commits car ca fait pas de sens d'avoir 5 fois le même commit. Lorsque je regarde d'un peu plus près ce que fait chacun de tes commits, je vois :
> 
> 1. un commit ou tu fais un changement de licence (donc ton libellé de commit ne fait pas de sens)
> 2. un commit avec un saut de ligne...  (donc ton libellé de commit ne fait pas de sens)
> 3. un commit ou tu fais un changement de licence (donc ton libellé de commit ne fait pas de sens)
> 4. un commit ou tu ajoutes un pbit (donc ton libellé de commit ne fait pas de sens)
> 5. un commit initial ou il se passe pas mal de chose, trop de choses... (modification du dbt_project, ajout d'une table, actualisation d'un schema. donc la aussi le libellé de ton commit ne fait pas de sens
> 
> On ne peut pas intégrer cette PR tel quel. il faut reorganiser tes commits et preciser clairement ce que tu fais ds ta PR. il n'y a pas qu'un "Changement `sex` à `genre` "

Tu vas devoir faire un _git rebase -i HEAD~X_ selon moi
X = nombre de commit dans ton historique que tu veux afficher. Dans ton cas, c'est 5.
Tu peux les squash et modifer le commit.

2024-12-17 19:25 UTC, gabrielThiffault commented
@gelinassCSSRS, quand j'ai essayé de rouler un build, j'ai eu deux erreurs : 

Compilation Error
  dbt found two schema.yml entries for the same resource named stg_activity_history. Resources and their associated columns may only be described a single time. To fix this, remove one of the resource entries for stg_activity_history in this file:
   - models/marts/human_resources/staging/activity/schema.yml

Compilation Error
  dbt found two schema.yml entries for the same resource named stg_main_job_history. Resources and their associated columns may only be described a single time. To fix this, remove one of the resource entries for stg_main_job_history in this file:
   - models/marts/human_resources/staging/activity/schema.yml
   
Je ne crois pas que ce soit pertinent de conserver le dossier human_resources/staging/**activity**, puisque les deux fichiers sont identiques à ce que l'on peut trouver dans le repo de Sciance. 

À discuter, mais ça cause un problème d'avoir les deux

2024-12-18 15:01 UTC, gabrielThiffault requested changes

2024-12-18 15:01 UTC, gabrielThiffault commented on reporting/human_resources/retirement/retirement.pbit
1. Réaligner les filtres pour être plus conviviaux : 
    1. Année, catégorie d'emploi, lieu de travail, type de retraite, statut d'engagement et genre?
2. Filtrer les années en ordre décroissant?
3. Modifier le logo, pour avoir le plus récent :
    1.  Disponible ici : https://shorturl.at/7AO47
4. Description détaillée pour chacun des onglets, dans la section _information_?

2024-12-19 20:09 UTC, gabrielThiffault requested changes

2024-12-19 20:09 UTC, gabrielThiffault commented on reporting/human_resources/retirement/retirement.pbit
Deux points :
1. Dans la bannière d'information dans le haut de chacune des pages, les filtres énumérés ne sont pas tous bons et peut-être besoin de reformuler : "Tous les filtres s'appliquent sur les valeurs prises au moment de la retraite : le lieu de travail, le **corps d'emplois** et le statut sont ceux effectifs au moment du départ en retraite." => Année, type de retraite et genre manquent
    1. Je propose : Il est possible de trier les retraites par année, catégorie d'emploi, lieu de travail, type de retraite, statut d'engagement et genre.

2. Sur la page "Nature départs retraite", la ligne de moyenne de certains graphiques est à 0 et celui de la distribution de l'âge du départ à la retraite de la page "Âge au départ de la retraite" est absent

@gelinassCSSRS, lâche pas, y'en reste pas gros!

2025-01-14 14:06 UTC, gabrielThiffault commented on reporting/human_resources/retirement/retirement.pbit
1. ![image](https://github.com/user-attachments/assets/2f798fdd-bd01-4d41-9e75-deceac3f07f6)
À l'onglet "Volumétrie départ à la retraite", la moyenne (#0D3B70) n'est pas de la même couleur que les autres (#53B6B2)

2025-01-14 14:08 UTC, gabrielThiffault requested changes

2025-01-14 14:08 UTC, gabrielThiffault commented on reporting/human_resources/retirement/retirement.pbit
Les filtres doivent être maintenus en naviguant entre chacune des pages, pour éviter à l'utilisateur d'avoir à les remettre.

2025-01-15 19:31 UTC, gabrielThiffault submitted a review, later dismissed

2025-01-15 19:31 UTC, gabrielThiffault commented
La PR est approuvée de mon côté

2025-01-27 19:18 UTC, sadqim submitted a review, later dismissed
LGTM!

2025-02-27 16:23 UTC, sadqim approved these changes

2025-02-27 16:25 UTC, gabrielThiffault approved these changes

2025-02-27 16:25 UTC, merged