feat: Utilisation de la variable mois_reference pour les tableaux Retirement
CDPVD/cdpvd_dashboards_store pull request #7
Opened 2024-12-16 20:27 UTC by gelinassCSSRS

# Objectives of the Pull Request ? 
Nous avons intégré dans le dbt_project un mois de référence pour permettre aux CSS d'indiquer le mois de leur début d'année scolaire. 
Comme nous ne pouvons pas changer les fichiers dans le projet core, nous avons du renommer les tables dans le projet CDPVD avec le préfix cdpvd.
Pour cette raison, nous avons du modifier le pbit aussi.

# What is left out of the Pull Request ? 
Nous avons modifié uniquement les tables que le projet retirement utilisait pour la date de référence. Nous n'avons pas migré tout les dossiers human_resources

# How to run the pull request ?
> Provide the code required to run the pull request. This is the code that will be used to review your pull request. **The provided code must work as-is. If a DBT error is raised while running the code, the PR will be rejected. The following code / placeholder is only provided as documentation / helper to get you started and you will need to adjust it.**

```bash
# Assuming you are in a folder containing both the core.data.store and the <cssXX>.data.store folder.
# Update the code
cd cdpvd.dashboards_store
git checkout feature/retraites_3
git pull
# Might be required if you update either the poetry file or the lock file
# poetry shell && poetry lock && poetry install 
cd ..cssrs.data.tbe
git checkout feature/retraites
git pull  
# Might be required if you add a new DBT dependency
# dbt deps
# Run dbt 
dbt build --select +tag:retirement 
```

# Checklist
> Please, read carefully each item before checking it. Your PR's review might be delayed otherwise.

* **Code** :
  * [x] The code I'm asking a review for is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x] My code follows the conventions described in the `contribution guide`.
  * [x] My `models` / `seeds` / `adapters` are tested and documented in DBT 9through the `yaml` files.
  * I have a added a new **mandatory seed** / a new **mandatory adapter** : 
    * [x] I have you populated the `tooling/nightly` project with my new seed / adapter.
    * [x] An exemple of how to populate the adapter can be found in the `analysis` folder.
  * I have added a new **dashboard** : 
    * [ ] I have updated the `core.dashboards_store/tooling/template/{{ cookiecutter.css_short_name + '.dashboards_store' }}/dbt_project.yml` file with my new dashboard. 
    * [ ] I have added a new `doc` page in the `core.dashboards_store/tooling/docs/content/` appropriate folder, describing what my dashboards does and how to configure it.
    * [x] The dashboard is saved with `.pbit` extension, **not** a `.pbix` extension, so it doesn't contains any data.
  * [x] I have called `sqfmt .` to format my code, and **made sure my code was still running as expected after having been reformated**.
* **Documentation** : 
  * [x]  I have updated the documentation (README) accordingly to my changes.
  * [x]  The models I have added are documented in a `schema.yml` file.
* **Pull-request** : 
  * [x]  My merge message is prefixed with a `commitizen` key word so it looks something like `<feat|fix|chore|doc|refactor|perf|style>: foo bar`**
  * [x]  The code *provided to run the pull request* is working. **I understand that my PR will be rejected as-is otherwise.**
  * [x]  My pull request is documented. I have explained the needs for the PR, what was left out of the it and why.
  * [x]  I have carefully reviewd each changes made to a file and made sure the files included on the PR were actually added on purpose.
  * [x]  I have assignee at least **1** people to review my PR.

2025-02-05 14:26 UTC, gabrielThiffault commented
### **Seed dans le répertoire CSS**
Il ne faut pas importer les schémas dans le répertoire du CSS : puisque ça fait un doublon.
Supprimer les deux fichiers :
![image](https://github.com/user-attachments/assets/18b19e54-1721-40ab-abbb-3e7b52254fcb)

2025-02-05 14:52 UTC, gabrielThiffault requested changes

2025-02-05 14:52 UTC, gabrielThiffault commented on reporting/human_resources/retirement/retirement.pbit
Peut-être partir du TdB de la dernière PR, pour avoir toutes les modifications ?

2025-02-05 20:37 UTC, gelinassCSSRS commented on reporting/human_resources/retirement/retirement.pbit
Étrange, quand je regarde les commits des 2 pr, ils semblent identique. même date. J'avais pris le temps de faire les modifications pour les 2 pr.

2025-02-20 13:51 UTC, gabrielThiffault requested changes

2025-02-20 13:51 UTC, gabrielThiffault commented on models/marts/human_resources/staging/activity/schema.yml
Pourquoi avoir modifiée la description de matr?
description: A flag indicating if the job schould be treated as the main job for this employee

2025-02-20 15:43 UTC, gabrielThiffault approved these changes

2025-02-27 16:09 UTC, sadqim approved these changes

2025-02-27 20:03 UTC, sadqim approved these changes

2025-02-28 15:16 UTC, gabrielThiffault approved these changes

2025-02-28 18:30 UTC, merged